### ISSUE TITLE
FR10.  Account Deletion 

### ISSUE THREAD

**Issue by gr9191** [WSU-4110/GymBuddy#13]
Goal: The system will allow user to delete their accounts
--
Stakeholders: Customers, engineers
When a customer no longer wishes to be a part of our platform, we will make it simple and straight forward for them to delete their account. This will remove their account from the matching pool as to speed up our systems and prevent false matches in the future. This will befit the customer and us by clearing up our system of inactive accounts. With one click we will remove the account from our systems.
Origin: Based on initial project specification document, team members came up with this description during the first meeting.
Version: 1.0 | Date: 1/31/21 | Priority: 1

**Comment by maherabdoualy** [comment]
We did not have time to cover this issue. To delete your account, email maherabdaly@gmail.com to ask the admin to delete your account.
