### ISSUE TITLE
FR11.  Notification for Matches 

### ISSUE THREAD

**Issue by gr9191** [WSU-4110/GymBuddy#14]
Goal: The system will notify the user when they have found a match.
--
Stakeholders: Customers
When a customer matches with another user they system should send both user a live notification. By sending these user notifications it makes it easier for the users to meet their end goal of finding a gym buddy. Allow the user the customize the notifications.
Origin: Based on initial project specification document, team members came up with this description during the first meeting.
Version: 1.0 | Date: 1/31/21 | Priority: 2

**Comment by maherabdoualy** [comment]
We did not have time to cover this issue.
