### ISSUE TITLE
FR12.  Uploading Pictures 

### ISSUE THREAD

**Issue by gr9191** [WSU-4110/GymBuddy#15]
Goal: The system will allow user to upload pictures of themselves
--
Stakeholders: Customers
When a customer customizes their profile, it has become standard for them to upload an image of themselves in order to better convey themselves to others. Since we are primarily visual creatures, we have adapted to derive a large quantity of information about an individual from looking at them. This means that it is imperative for users to see who they are swiping on. There will be an upload arrow in which users can add photos through their camera roll. These photos will be compressed in order to save on file space.
Origin: Based on initial project specification document, team members came up with this description during the first meeting.
Version: 1.0 | Date: 1/31/21 | Priority: 2

**Comment by maherabdoualy** [comment]
We did not have time to cover this issue.

**Comment by KevinClause** [comment]
We were unable to design a profile system that would include user uploaded images given our recent switch to android studio and lack of background in this new IDE
