### ISSUE TITLE
FR13.  Blocking option 

### ISSUE THREAD

**Issue by gr9191** [WSU-4110/GymBuddy#18]
Goal: The system should allow the user to block any user they want.
--
Stakeholders: Customers
The app allows users to block any user in order to help maintain an environment that is safe and fun for everyone. Some users can be inappropriate and this feature will allow users to filter who they talk to.
Origin: Based on initial project specification document, team members came up with this description during the first meeting.
Version: 1.0 | Date: 1/31/21 | Priority: 1

**Comment by maherabdoualy** [comment]
We did not have time to cover this issue.

**Comment by KevinClause** [comment]
We had issues with re-implementing our messaging app in an android environment and therefore did not get to this.
