### ISSUE TITLE
FR14.  Muting options 

### ISSUE THREAD

**Issue by gr9191** [WSU-4110/GymBuddy#19]
Goal: The system should allow the user to mute any user they want.
--
Stakeholders: Customers
Another feature is a user would be able to mute another user for a certain period of time. It’s a way to get rid of undesirable messages from other users.
Origin: Based on initial project specification document, team members came up with this description during the first meeting.
Version: 1.0 | Date: 1/31/21 | Priority: 2

**Comment by maherabdoualy** [comment]
We did not have time to cover this issue.

**Comment by KevinClause** [comment]
We had issues with re-implementing our messaging app in an android environment and therefore did not get to this.
