### ISSUE TITLE
FR16.  Reporting Function 

### ISSUE THREAD

**Issue by gr9191** [WSU-4110/GymBuddy#21]
Goal: The system should allow the users to report any individual who posts inappropriate messages and or images to the app.
--
Stakeholders: Customers
This would allow for a general policing of the app. We do NOT want users to be posting lewd content to the application and will employ the help of other users to prevent this type of content from being posted to the app. Additionally if we have a user sending unwarranted and inappropriate messages to another user, they will have the choice to report the other user.
Origin: Based on initial project specification document, team members came up with this description during the first meeting.
Version: 1.0 | Date: 1/31/21 | Priority: 1

**Comment by maherabdoualy** [comment]
We did not have time to cover this issue.

**Comment by maherabdoualy** [comment]
To report an account, for now you can email the admin maherabdaly@gmail.com and report the user, the admin will have to manually disable the account if we find that the user goes our community guidelines.
