### ISSUE TITLE
FR6.  Light/Dark Mode 

### ISSUE THREAD

**Issue by gr9191** [WSU-4110/GymBuddy#8]
Goal: The system allows the user to switch themes between light and dark.
--
Stakeholders: Users
Gives the users the options to change their profile design between light and dark mode giving a lighter or darker tint for design.
Origin: Based on initial project specification document, team members came up with this description during the first meeting.
Version: 1.0 | Date: 01/30/2021 | Priority:  4

**Comment by maherabdoualy** [comment]
We did not have time to cover this issue.

**Comment by KevinClause** [comment]
we have decided that this issue was non-essential and there fore will not be covered.
